### ISSUE TITLE
RoE Record Implementation Tracker

### ISSUE THREAD

**Issue by Kreidos** [project-topaz/topaz#1521]
I'll try to keep this list updated and note sections which already have someone working on them. A checkmark on a category means that section is 100% complete; Otherwise, a rough percentage will be noted next to each if some are done.

Please contact me before starting work on a category, as there are a few persons already undertaking them, and I'd hate your hard work be for naught when someone else PRs it first.

### Special ###

 - [x] Limited-time Challenges (4-hour)

### Tutorial ###

 - [ ] Basics **90%** - Trust records only in Trust/Canary branch
 - [ ] Intermediate
 - [ ] Synthesis
 - [ ] Quests 1 **5%**
 - [ ] Quests (Artifact 1)
 - [ ] Quests (Artifact 2)
 - [ ] Quests (Artifact 3)
 - [ ] Level Cap Increase **75%**
 - [x] Storage Expansion
 - [ ] Quests (Weapon Skills)
 - [ ] Missions (Rhapsodies of Vana'diel)
 - [ ] Missions (San d'Oria) (**WIP** Claywar)
 - [ ] Missions (Bastok) - **5%** (**WIP** Claywar)
 - [ ] Missions (Windurst) (**WIP** Claywar)
 - [ ] Missions (Zilart) (**WIP** Claywar)
 - [ ] Missions (Promathia)
 - [ ] Missions (Aht Urhgan)
 - [ ] Missions (Altana)
 - [ ] Missions (Adoulin)

### Combat (Wide Area) ###

 - [x] Combat (General)
 - [x] Combat (Spoils) 1
 - [x] Combat (Spoils) 2

### Combat (Region) ###

 - [x] Combat (Original Areas 1)
 - [x] Combat (Original Areas 2)
 - [x] Combat (Original Areas 3)
 - [x] Combat (Original Areas 4)
 - [ ] Combat (Adoulin 1)
 - [ ] Combat (Adoulin 2)
 - [x] Combat (Zilart 1)
 - [x] Combat (Zilart 2)
 - [x] Combat (Promathia 1)
 - [x] Combat (Promathia 2)
 - [x] Combat (Aht Urhgan)
 - [x] Combat (Goddess 1)
 - [x] Combat (Goddess 2)
 - [x] Combat (Abyssea)
 - [ ] Combat (Escha 1)
 - [ ] Combat (Escha 2)

### Fishing ###

 - [ ] Fishing: General
 - [ ] Fishing: Tenacity

### Crafting ###

 - [x] Crafting: General
 - [ ] Crafting: Escutcheons (Woodworking)
 - [ ] Crafting: Escutcheons (Clothcraft)
 - [ ] Crafting: Escutcheons (Alchemy)
 - [ ] Crafting: Escutcheons (Bonecraft)
 - [ ] Crafting: Escutcheons (Cooking)
 - [ ] Crafting: Escutcheons (Goldsmithing)
 - [ ] Crafting: Escutcheons (Leathercraft)
 - [ ] Crafting: Escutcheons (Smithing)

### Harvesting ###

 - [ ] Harvesting (General)
 - [ ] Harvesting (Original Areas)
 - [ ] Harvesting (Adoulin 1)
 - [ ] Harvesting (Zilart)
 - [ ] Harvesting (Promathia)
 - [ ] Harvesting (Aht Urhgan)
 - [ ] Harvesting (Goddess)
 - [ ] Harvesting (Abyssea)

### Content ###

 - [ ] Content (Ambuscade)
 - [ ] Lair Reives
 - [ ] Colonization Reives
 - [ ] Wildskeeper Reives
 - [ ] Content (Other)
 - [ ] Content (Dynamis 1)
 - [ ] Content (Dynamis 2)
 - [ ] Content (Limbus)
 - [ ] Content (ZNM)
 - [ ] Content (Vagary)
 - [ ] Content (Omen)
 - [ ] A.M.A.N. Trove
 - [ ] Content (Odyssey)

### Achievements ###

 - [x] Job Levels 1
 - [ ] Job Levels 2 (**WIP** @Apocarypse)
 - [ ] Job Levels 3 (**WIP** @Apocarypse)
 - [ ] Job Levels 4 (**WIP** @Apocarypse)
 - [ ] Fame (**WIP** @Apocarypse)

### Unity ###

 - [ ] Unity (Shared A)
 - [ ] Unity (Shared B)
 - [ ] Unity (Shared C)
 - [ ] Unity (Shared D)
 - [ ] Unity (Shared E)
 - [ ] Unity (Shared F)
 - [ ] Unity (Aldo)
 - [ ] Unity (Apururu)
 - [ ] Unity (Ayame)
 - [ ] Unity (Flaviria)
 - [ ] Unity (Invincible Shield)
 - [ ] Unity (Jakoh Wahcondalo)
 - [ ] Unity (Maat)
 - [ ] Unity (Naja Salaheem)
 - [ ] Unity (Pieuje)
 - [ ] Unity (Sylvie)
 - [ ] Unity (Yoran-Oran)
 - [ ] Unity (Wanted)

### Vana'versary ###

 - [ ] 15th Vana'versary I
 - [ ] 15th Vana'versary II
 - [ ] 15th Vana'versary III
 - [ ] 15th Vana'versary IV
 - [ ] 15th Vana'versary V
 - [ ] 17th Vana'versary

### Other ###

 - [ ] RoE Quests
 - [ ] RoE Quests 2
 - [ ] RoE Quests 3
 - [x] Daily Objectives
 - [ ] Monthly Objectives

**Comment by ghost** [comment]
Bastok, San d'Oria, and Windurst missions are implemented on a local branch.  Testing now, and if anyone could suggest a faster way than running through manually I'd be greatly appreciative.  !add/completemission seems to fail a lot in many cases.
